lib/global_uid.rb
lib/global_uid/has_and_belongs_to_many_builder_extension.rb
test/global_uid_test.rb

:koala:
Inherit the global_uid_disabled state of models from the left-hand-side of a has_and_belongs_to_many association. Without this patch, any models using has_and_belongs_to_many that also have Global UID disabled will get Global UID errors on the join table association complaining that the corresponding table for that model does not exist.
Conceptually similar to https://github.com/zendesk/active_record_shards/commit/6c740539b3f2a3d9f98148424ae37056ed16b1be
/cc @zendesk/quokka @bquorning @pschambacher @grosser @osheroff
- Only fixes the problem on Rails 4.1+
- Change in behaviour for has_and_belongs_to_many associations if the previous behaviour was expected

Inherit global_uid_disabled from LHS of HABTM associations on Rails 4.1+

---

gemfiles/rails3.2.gemfile.lock
gemfiles/rails4.0.gemfile.lock
gemfiles/rails4.1.gemfile.lock
gemfiles/rails4.2.gemfile.lock
lib/global_uid/active_record_extension.rb
lib/global_uid/base.rb
test/global_uid_test.rb

`generate_many_uids` was removed in the last wave of [Rails 4.x upgrading](https://github.com/zendesk/global_uid/pull/22)
Sometimes, allocating uid's in bulk is useful.
Generating 1000 uid's one at a time takes about half a second locally:
```
zendesk(dev)> Benchmark.realtime { 1000.times { ActiveRecord::Base.connection.insert "replace into global_uids_1.tickets_ids (stub) values ('a')" } }
=> 0.604114233
```
I thought maybe wrapping that in a transaction would help, but it didn't:
```
zendesk(dev)> Benchmark.realtime { ActiveRecord::Base.transaction { 1000.times { ActiveRecord::Base.connection.insert "replace into global_uids_1.tickets_ids (stub) values ('a')" } } }
=> 0.681438674
```
Now check this out, a single SQL statement with a multiple-row insert of 1000 rows (which of course all …

Simpler implementation of generate_many_uids

---

lib/global_uid.rb

@zendesk/octo @osheroff 
I didn't look *too* hard, but I couldn't actually find a schema_migrations table during these tests, is it just disabled if it doesn't exist?

don't use global_uids for SchemaMigration model

---

.travis.yml
gemfiles/rails4.1.gemfile.lock
lib/global_uid.rb
lib/global_uid/has_and_belongs_to_many_builder_extension.rb

:octopus::computer:
/cc @grosser @bquorning 
Waiting for https://bugs.ruby-lang.org/issues/11120 to be fixed, we'll do with shitty code...
* active_record_shards and active_record_host_pools PRs are merged, released and enforced here
* None

Revert Module.prepend and replace alias_method_chain with alias_method

---

lib/global_uid/base.rb
test/global_uid_test.rb

We encountered a bug where global_uid could produce duplicate ids. This happens when a MySQL connection is established in the parent process (e.g. unicorn), not being reset on `fork`, so that all the child processes share the same client. This causes a race between the execution of `mysql_query ` and `mysql_insert_id` in the underlying c client, causing one process to read the insert id state of the other process.
global_uid does have thread-local protection, but (surprise) when ruby forks the parent's thread local storage is readable by the child.
```ruby
Thread.current[:foo] = "set in the parent"
puts "#{$$}: #{Thread.current.inspect}, #{Thread.current[:foo].inspect}"
fork do
puts "#{$$}: #{Thread.current.inspect}, #{Thread.current[:foo].inspect}"
end
```
Output:
```
20256: …
```

INFR-2968 Reset MySQL connections after fork

---

lib/global_uid/active_record_extension.rb

/cc @grosser @bquorning @gabetax 
Fixing the error introduced in https://github.com/zendesk/global_uid/pull/39 and noticed by @bquorning

Fix logic involving existence of global_uid_table_exists

---

lib/global_uid/active_record_extension.rb

Instead of a `StandardError` "Global UID table foo_ids not found!" you will now just get a `Mysql2::Error` "Table 'bar.foo_ids' doesn't exist".

Remove unnecessary table existence check

---

lib/global_uid.rb

General ruby convention is to not rescue `StandardError` but not `Exception`. By extension, custom errors should inherit from `StandardError`. The custom GlobalUid exceptions were not doing that. I don't see any reason why that's intentional.
I found myself in this situation because stock webrick (v1.4.2 / ruby v2.5.0), with RAILS_ENV=test, will return uncaught `Exception`s into 200s. Why? Beat's me! puma works fine. unicorn just crashes without a response.
cc @zendesk/cask @bquorning @grosser @staugaard @pschambacher
Previously these exceptions would have been ignored by `StandardError` handlers. It may be surprising when these begin getting handled, but they should have been handled the entire time.

Custom exceptions should inherit from StandardError

---

.github/CODEOWNERS
global_uid.gemspec

Adds current maintainers to gemspec, but keep names of previous contributors.

Add information on current gem maintainers

---

lib/global_uid/migration_extension.rb
test/global_uid_test.rb
test/migrations.rb

Currently database migrations run with active record 5.1 will fail to properly create a table with an `id` column. 
Summary:
```
class CreateMyRecords < ActiveRecord::Migration[5.0]
def change
create_table :my_records do |t|
end
end
```
Result
```
CREATE TABLE `my_records` (
`integer` int(10) NOT NULL,
PRIMARY KEY (`integer`)
)
```
What is the issue?
`integer` int(10) NOT NULL
The primary key is getting created with the name of the data type instead of the column name.
This PR removes functionality that broke in AR5.1, which previously allowed a user to specify the id column name. This does not appear to be in use at Zendesk.

remove named id column functionality that breaks in rails 5.1

---

test/global_uid_test.rb

This project was using a mix of minitest syntaxes (e.g. `assert_equal` and `must_equal`). I really want to switch to RSpec, but I really don’t want to spend the time doing it anyway :-)

Minitest fixes

---

README.md
global_uid.gemspec

Most important changes are:
- Removed support for Ruby 2.3
- Added support for ActiveRecord 6.0

Release v3.7.1

---

lib/global_uid.rb
test/global_uid_test.rb

The gemspec ensures that ActiveRecord is at least v4.2.0.
https://github.com/zendesk/global_uid/pull/62/files?w=1 for readable diff.

Remove code checking for old Rails versions

---

Changelog.md
README.md
lib/global_uid/active_record_extension.rb
lib/global_uid/base.rb
lib/global_uid/migration_extension.rb
test/global_uid_test.rb

The flag was false by default. It adds complexity to the code and can be confused with the other disabled states `use_global_uid`, the `global_uid_options[:disabled]` option and `global_uid_disabled` on the model.
Use `global_uid_options[:disabled]` if you want to disable the functionality. There's a performance spec for benchmarking included in dc1f998

Remove the concept of `dry_run`

---

Changelog.md
lib/global_uid/active_record_extension.rb
lib/global_uid/base.rb
lib/global_uid/migration_extension.rb

In the following cases we were passing options around but never using them, [leftover from a previous implementation but never used](https://github.com/zendesk/global_uid/commit/2744dff891091053adfecb42718c6126c52acf78#diff-a485bda32508290d377722bde6530880R120-R123). I found them misleading as whatever you passed in would ultimately be ignored.
I've removed them so the code is more explicit and hopefully a little less confusing.

Remove unused and often misleading `options`

---

Changelog.md
README.md
lib/global_uid.rb
lib/global_uid/allocator.rb
lib/global_uid/base.rb
test/lib/allocator_test.rb
test/lib/global_uid_test.rb

This patch adds `auto_increment_increment` validation to the following scenarios:
* Connection initialization
* Allocating one ID
* Allocating multiple IDs
A lot of refactoring was done as part of this PR and has either been merged separately or moved to https://github.com/zendesk/global_uid/pull/70
These changes have been benchmarked, should have no noticeable impact to performance and continue to be thread safe.
Validation during initialization is done by comparing the client configuration (`increment_by`) with each alloc server (`auto_increment_increment`). If the server is misconfigured, an error is reported via the `notifier` (defaults to error logs) and it's removed from the pool. The connection will be retried every 10 minutes (configurable via the `connection_retry`) indefinitely. …

auto_increment_increment validation

---

Changelog.md
lib/global_uid.rb
lib/global_uid/active_record_extension.rb
lib/global_uid/allocator.rb
lib/global_uid/base.rb
lib/global_uid/migration_extension.rb
lib/global_uid/server.rb
test/lib/global_uid_test.rb
test/performance/creation_test.rb
test/test_helper.rb

Talking it over with @bquorning, there was a lot of changes being made in #70 and it made reviewing difficult. This work is split out from #70 and broken down further.
This patch is a large rework of the internals, adding a Server class which is responsible for all connection handling, moving it out of the GlobalUid::Base, and moving it to private accessors where necessary.
Prior to this, clients could do things they probably shouldn't and as such this patch **includes many breaking changes**, making it harder to reach into the internals.
Due to the amount of change I've tried to keep my commits small to make reviewing easier, commits are either moving code or modifying it, never both at the same time.

Move alloc connection handling into new GlobalUid::Server class 

---

Changelog.md
README.md
lib/global_uid.rb
lib/global_uid/active_record_extension.rb
lib/global_uid/allocator.rb
lib/global_uid/base.rb
lib/global_uid/configuration.rb
lib/global_uid/migration_extension.rb
test/lib/global_uid_test.rb
test/test_helper.rb

**Breaking change**, _Split out from #70_
The gem is now configured like many others, with options like `storage_engine` now being documented.
Clients upgrading will need to update their configuration as the previous implementation is no longer supported.
All supported configuration options live in `GlobalUid::Configuration`, with their respective defaults. New clients of the gem need only set `id_servers` and `increment_by` unless they have a more bespoke setup.
To configure the gem, add the following in a Rails initializer
```
GlobalUid.configure do |config|
config.id_servers = [ 'id_server_1', 'id_server_2' ]
config.increment_by = 5
}
```

Add GlobalUid::Configuration class

---

Changelog.md
docs/upgrading-to-4-0.md
global_uid.gemspec

This release includes non-backwards compatible changes. 
* The `auto_increment_increment` on the allocation servers is compared with the configured `increment_by` and an exception is raised if they don't match. Use the `suppress_increment_exceptions` configuration option if this is expected.
* Make sure you weren't using any of the private APIs that were removed in https://github.com/zendesk/global_uid/pull/71.
* The `GlobalUid::ServerVariables` module has been removed (https://github.com/zendesk/global_uid/pull/66), update your database.yml to configure the increment and offset values for the development/test DB.
* Update your configuration to use the new interface (https://github.com/zendesk/global_uid/pull/72).
```ruby
GlobalUid.configure do |config|
config.id_servers = [ …
```

Release v4.0.0.beta1

---

Changelog.md
lib/global_uid/migration_extension.rb
lib/global_uid/server.rb
lib/global_uid/test_support.rb
test/lib/test_support_test.rb

Clients using earlier versions of the gem would execute code like the following block when restoring the database from a schema dump.
```ruby
unless GlobalUid::Base.global_uid_options[:disabled]
non_global_uid_tables = ["ar_internal_metadata"]
table_list = ActiveRecord::Base.connection.data_sources
(table_list - non_global_uid_tables).each do |table|
GlobalUid::Base.drop_uid_tables(table + "_ids")
GlobalUid::Base.create_uid_tables(table + "_ids", options)
end
end
```
If the schema dump doesn't include global_uid table information, this patch allows them to create the ID tables after the fact. For example, the code above should be updated to:
```ruby
require 'global_uid/test_support'
table_list = ActiveRecord::Base.connection.data_sources - ["ar_internal_metadata"] …
```

Add GlobalUid::TestSupport for recreating ID tables in test environments

---

lib/global_uid/test_support.rb

Merging https://github.com/zendesk/global_uid/pull/76 after https://github.com/zendesk/global_uid/pull/77 broke master. The method was moved to the GlobalUid module. 
This patch updates the stale references.

Fix build after merge

---

Changelog.md
global_uid.gemspec

Cutting a release with the following changes:
- A `GlobalUid::TestSupport` module has been introduced to assist with creating, droppping and recreating ID tables. (https://github.com/zendesk/global_uid/pull/76)
- `GlobalUid.enabled?`, `GlobalUid.disabled?`, `GlobalUid.disable!` & `GlobalUid.enable!` helper methods added. (https://github.com/zendesk/global_uid/pull/77)

v4.0.0.beta2

---

test/lib/global_uid_test.rb
test/support/migrations.rb
test/support/models.rb

Clients can pass in a `start_id` when creating the UID tables but we had
no spec coverage for it. Ensure the functionality works as expected.

Add test for table start_id option

---

Changelog.md
lib/global_uid/active_record_extension.rb
lib/global_uid/allocator.rb
lib/global_uid/base.rb
lib/global_uid/server.rb
test/lib/allocator_test.rb
test/lib/global_uid_test.rb
test/support/migrations.rb
test/support/models.rb
test/test_helper.rb

Each model using global_uids has an ID table created for it on the
allocation server. If we're keeping track of recently allocated IDs, we
need to scope it by table name as the sequence between tables will be
different.
To resolve this, the Server now contains a hash of Allocators, keyed by 
table name. The Server will validate the `increment_by` value on the DB
during connection initialization, and whenever an allocation is made
we'll create or retrieve an allocator for that table, using validated
connection reference.
The connection validation was moved to reduce overhead, performing
it per table, per process would impact performance and as a result of
this, some of the specs have been moved around.

Fix validation error when working with multiple models

---

Changelog.md
global_uid.gemspec

Moving from beta to release candidate as the changes have been verified using a client in a staging/integration environment. Will move to 4.0.0 once it's been used in production.
- ID allocation validation now takes the table name into consideration. Prior to this change the server would allocate multiple IDs (e.g. 2 & 2) from different tables using global UIDs and incorrectly raise a InvalidIncrementException. (https://github.com/zendesk/global_uid/pull/81)

v4.0.0.rc1

---

Changelog.md
lib/global_uid/active_record_extension.rb
test/lib/global_uid_test.rb

The implementation changed during the move to v4 and generating one ID would return the ID itself instead of an array.
With this patch, `generate_many_uids` will once again return an array, no matter the count.

Fix generate_many_ids(1), should return an array.

---

.circleci/config.yml
gemfiles/rails6.1.gemfile
global_uid.gemspec
lib/global_uid/server.rb
test/lib/global_uid_test.rb

~There is a deprecation warning that we should probably fix:~
DEPRECATION WARNING: to_h is deprecated and will be removed from Rails 6.2 (You can use
`ActiveRecord::Base.configurations.configs_for(env_name: 'env', name: 'primary').configuration_hash` to get
the configuration hashes.) (called from mysql2_connection at [...]/global_uid/lib/global_uid/server.rb:96)
Fixed!
In Rails 6.1, the database configurations, and each database configuration, are now real objects. And the hash representation of a database configuration has symbolized keys in Rails 6.1. With these few changes in mind, we actually need only a few changes for making this gem compatible with 6.1.

Allow using with Rails 6.1

---

.circleci/config.yml
Changelog.md
global_uid.gemspec

Had to switch to the `cimg/ruby:3.1.2` image since the other image was not found.
Had to keep `minitest` at `v5.15.0` in order to bundle with the Ruby versions we're testing. There are other ways of handling this but this seems simplest for a gem that's supposed to be archived.

Test with Ruby 3.1

---

.github/workflows/publish.yml

Creates a workflow for publishing to the public Zendesk RubyGems account.
Uses the workflow from the public `gw` gem. `gw`'s [ruby-gem-publication readme](https://github.com/zendesk/gw/blob/main/ruby-gem-publication/README.md)

Add workflow for publishing to rubygems
